version: 2
jobs:
  create-tar:
    docker:
       - image: quay.io/quintype/black-knight:bk-rubyupgrade

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install ruby dependencies
          command: |
            /root/.rbenv/shims/bundle install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependency-cache-

      - run:
          name: install npm dependencies
          command: |
            npm install

      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: create tar
          command: |
            make create-tar
            mkdir -p /tmp/workspace
            mv black-knight.tar /tmp/workspace/black-knight.tar
            date '+%Y-%m-%d-%T' > /tmp/workspace/time.txt


      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - black-knight.tar
            - time.txt

      - store_artifacts:
          path: /tmp/workspace/time.txt
          destination: time.txt

  upload-artifact:
    docker:
       - image: python:2.7-alpine3.7

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Install aws cli
          command: pip install awscli

      - run:
          name: upload artifact
          command: |
            aws s3 cp /tmp/workspace/black-knight.tar  s3://qt-deploy-artifacts/black-knight/$(cat /tmp/workspace/time.txt)/black-knight.tar

workflows:
  version: 2
  pipeline:
    jobs:
      - create-tar
      - upload-artifact:
          requires:
            - create-tar
          context: artifacts
