# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: postgresql

development:
  adapter: async

test:
  adapter: async
