# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5dfb7d34aab5d28b91b093f1c6826cbfb32aa94c0faceb5d012725879f74350e3612f8f8d99f163a2d3c20003539fe06d0ea1ebc342ed5b45cc6516b7f351b
  qt_environment: staging
  kube_master: 172.31.25.114:8080
  default_url_options: localhost:10001
  TWO_FACTOR_SECRET_KEY: 9281e50d3304fda4372883f534731b2e9dbd0d3bafddabc193d8d06f835fdbcdea557c2af3f0af4d3c9f08e05ff954423c0d436e6cc7dd9e59b24d1de9a03a11
  slack_hook: https://hooks.slack.com/services/your/hook/here

test:
  secret_key_base: ed64b58052b52eaf7866bd048be8a14edc46a183c6a6f8758b10fdbd3efef1bc9fe779a1f74d5e228472b40959f6ff2b5ec199be52d0960416f9d6c47fd80fe4
  qt_environment: staging
  kube_master: 0.0.0.0:8080
  default_url_options: localhost:10001
  TWO_FACTOR_SECRET_KEY: 9281e50d3304fda4372883f534731b2e9dbd0d3bafddabc193d8d06f835fdbcdea557c2af3f0af4d3c9f08e05ff954423c0d436e6cc7dd9e59b24d1de9a03a11
  slack_hook: https://hooks.slack.com/services/your/hook/here
